const View = require('./View');

const initialize = () => {
    const view = new View();
    const text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mi proin sed libero enim sed. Facilisis mauris sit amet massa vitae tortor. Risus feugiat in ante metus dictum. Urna id volutpat lacus laoreet non. Quis hendrerit dolor magna eget est lorem ipsum dolor. In hendrerit gravida rutrum quisque non. Id volutpat lacus laoreet non curabitur gravida arcu. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Augue neque gravida in fermentum et sollicitudin ac. Adipiscing diam donec adipiscing tristique risus nec.'+
    'Auctor eu augue ut lectus arcu bibendum. Quis risus sed vulputate odio. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Sit amet facilisis magna etiam. Dictum fusce ut placerat orci nulla pellentesque dignissim. Dignissim suspendisse in est ante in. Fames ac turpis egestas sed tempus urna et pharetra. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Sit amet purus gravida quis blandit turpis. Adipiscing diam donec adipiscing tristique risus nec. Mattis nunc sed blandit libero. Dui nunc mattis enim ut.' +    
    'Velit egestas dui id ornare arcu odio. Vitae et leo duis ut diam quam nulla porttitor massa. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Convallis a cras semper auctor neque vitae tempus. In eu mi bibendum neque egestas congue. Ridiculus mus mauris vitae ultricies leo integer. Enim ut tellus elementum sagittis vitae et leo duis. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Scelerisque eu ultrices vitae auctor eu augue ut. In nibh mauris cursus mattis molestie. Vulputate ut pharetra sit amet aliquam. Varius quam quisque id diam vel quam elementum pulvinar. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Fusce id velit ut tortor pretium viverra. Purus in mollis nunc sed id semper. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque.' +
    'Morbi tempus iaculis urna id. Vitae ultricies leo integer malesuada. Mattis molestie a iaculis at erat pellentesque adipiscing commodo. Pellentesque eu tincidunt tortor aliquam nulla facilisi. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Tempus imperdiet nulla malesuada pellentesque. Amet nulla facilisi morbi tempus iaculis. Lorem donec massa sapien faucibus et molestie. In massa tempor nec feugiat nisl pretium. Id cursus metus aliquam eleifend mi. Eget velit aliquet sagittis id consectetur purus ut. Faucibus interdum posuere lorem ipsum dolor sit amet. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Lorem ipsum dolor sit amet consectetur adipiscing elit duis tristique. Aliquam eleifend mi in nulla.' + 
    'Orci eu lobortis elementum nibh tellus molestie nunc non blandit. Proin gravida hendrerit lectus a. Pharetra et ultrices neque ornare aenean euismod elementum nisi. Commodo ullamcorper a lacus vestibulum sed. Dictumst quisque sagittis purus sit amet volutpat consequat. Etiam tempor orci eu lobortis elementum nibh tellus molestie nunc. Pretium nibh ipsum consequat nisl vel pretium lectus. Integer eget aliquet nibh praesent tristique magna sit amet. Blandit massa enim nec dui nunc. Sed lectus vestibulum mattis ullamcorper velit. At consectetur lorem donec massa sapien faucibus et. Ultrices eros in cursus turpis massa tincidunt dui. Semper auctor neque vitae tempus. Laoreet non curabitur gravida arcu. Adipiscing enim eu turpis egestas pretium aenean pharetra. Non pulvinar neque laoreet suspendisse interdum consectetur libero id. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Egestas congue quisque egestas diam in arcu cursus euismod. Nam at lectus urna duis convallis convallis tellus id interdum. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget.'


    view.createText(text);
}

initialize();